astropy/ccdproc

CHANGES.rst
docs/changelog.rst
docs/conf.py
docs/index.rst

A reference to the changelog was added to index.rst
Note of chagnes added in CHANGES.rst

changelog.rst was added to /ccdproc/docs so as to link to CHANGES.rst

---

.travis.yml
docs/rtd-pip-requirements

This also updates the minimum requirements for readthedocs.
Closes #188

Change all travis tests to use astropy development

---

CHANGES.rst
ccdproc/combiner.py
ccdproc/tests/test_combiner.py

Ensure dtype of combined image matches Combiner dtype

---

ccdproc/core.py
ccdproc/tests/test_ccdproc.py

Changed subtract_overscan to properly return a new value for the data

---

.gitignore
ah_bootstrap.py

This fixes `python setup.py build_sphinx` for Sphinx 1.3+.

Updated astropy-helpers to v1.0.2

---

ccdproc/tests/test_ccdproc.py

tests added for core.py functions as requested in issue 117

---

.travis.yml

See this for details: http://docs.travis-ci.com/user/migrating-from-legacy/

Opt in to new container-based builds on travis

---

docs/ccdproc/index.rst

The example given in the documentation does not provide in-place
operation, since this is not available (yet) in ccdproc.

Remove mention about in-place operation

---

ccdproc/core.py
ccdproc/tests/test_ccdproc.py

Closes #240 using the fix from @wschoenell

Fix overscan subtraction on non-square image

---

CHANGES.rst

This PR updates the changelog through the most recent released version.

Update changleog through release 0.3.1

---

ccdproc/image_collection.py
ccdproc/tests/test_image_collection.py

Raised a warning if there are no fits files in an ImageFileCollection. Created test_no_fits_files_in_collection to check this change.
Edit: closes #239

Addressing issue #239

---

ccdproc/ccddata.py
ccdproc/tests/test_ccddata.py

Add WCS setter

---

.travis.yml

Add python 3.5 to travis test matrix

---

ccdproc/combiner.py

Change an informative print function to astropy.log.info(), and remove
a try-except clause with superfluous print functions.
Closes #266

Remove use of print function for non-explicit output

---

CHANGES.rst
ccdproc/ccddata.py
ccdproc/tests/test_ccddata.py
docs/ccdproc/ccddata.rst

Modifies CCDData arithmetic with number/Quantity to preserve WCS

---

ccdproc/ccddata.py
ccdproc/tests/test_ccddata.py

Update how compare_wcs is handled in ccddata arithmetic to match the current handling in the development version of astropy.

New wcs arith

---

ccdproc/core.py

Fix non-integer indexes for future numpy versions

---

ccdproc/ccddata.py
ccdproc/tests/test_ccddata.py

writing multi extension fits files with mask, uncertainty

---

CHANGES.rst

Forgot to mention #302 in the changes.rst.

documentation for writing mask, uncertainty as extension [skip ci]

---

CHANGES.rst
appveyor.yml
ccdproc/image_collection.py
ccdproc/utils/collections.py

Removing python2.6 workarounds

---

CHANGES.rst
ccdproc/ccddata.py
ccdproc/tests/test_ccddata.py

Fixes #291.
I've included a test and changelog entry.

fixes add/subtract arithmetics with quantities of different unit.

---

ccdproc/image_collection.py
ccdproc/tests/test_image_collection.py

Return base name instead of full path in ImageFileCollection iterators

---

ccdproc/ccddata.py

updated CCDData.read/write doc

---

AUTHORS.rst
CHANGES.rst
ccdproc/ccddata.py
ccdproc/core.py
ccdproc/tests/test_ccddata.py
ccdproc/tests/test_ccdproc.py
docs/ccdproc/reduction_toolbox.rst

This is the first pull request for adding a ccd_process task that has all the reductions steps in one function.

added ccd_process to core

---

AUTHORS.rst
CHANGES.rst

Update for the recent pull request.
@EP-Guy -- I have you listed at the moment only as EP-Guy in the authors list...please let me know if you want me to add a name!

Update AUTHORS and CHANGES [ci skip]

---

ccdproc/tests/test_ccdproc.py

Fix another issue with a float used as index

---

docs/ccdproc/index.rst

Just a grammar issue in line 100 and a dead sentence in line 97

Cleanup update of index.rst

---

CHANGES.rst
ccdproc/core.py
ccdproc/tests/test_ccdproc.py

This should fix #345 by doing a slight rearrangement of the calculations in `flat_correct`

Ensure uncertainty is scaled properly in flat_correct

---

CHANGES.rst
ccdproc/ccddata.py
ccdproc/image_collection.py
ccdproc/tests/test_ccddata.py

This address #355 in the short term by constructing our own list of fits formats.

Autoidentify extension fts as a FITS file

---

ccdproc/tests/test_image_collection.py

to be consistent with rest of the package

Importing pytest from astropy

---

ccdproc/core.py

Fixes #342 by removing the check if the ``transform_func`` is a callable. However if the first call to `transform_func` fails with a `TypeError` containing `is not callable` then a more informative exception is raised.
Actually I'm pretty sure I've seen a context manager for exactly this type of `try ... except ...` but I can't find it at the moment. Maybe it was in some external package.

removed test if transform_func is a callable in transform_image

---

CHANGES.rst
ccdproc/image_collection.py
ccdproc/tests/test_image_collection.py
docs/ccdproc/image_management.rst

Hello everyone,
Is this the right approach to implement #400?
I used ``'adu'`` as the default unit to instantiate an CCDData object in case ``'BUNIT'`` is not present in the ``header``. I'm not sure if that is intended. Should the ccddata unit be given as parameter somehow (for instance, through ``kwd``)?
Thanks!

CCDData generator for ImageCollection

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

The issue and pr template are explained in https://github.com/blog/2111-issue-and-pull-request-templates.
The contribution guideline is explained here: https://github.com/blog/1184-contributing-guidelines
Text is provisional!

Add issue and pull request template and links to the astropy contributing guidelines

---

CHANGES.rst

There won't be a 1.1.1 release (I think) so I've moved those entries to 1.2.0

Removed 1.1.1 section of the changelog.

---

CHANGES.rst
ccdproc/core.py
ccdproc/tests/test_wrapped_external_funcs.py
docs/ccdproc/reduction_toolbox.rst

Median filter wrapper

---

CHANGES.rst
ccdproc/combiner.py
ccdproc/tests/test_combiner.py

Add combine_uncertainty_func parameter to combine.

---

ccdproc/tests/test_ccddata.py

This adds tests for the features added in #426.
@crawfordsm Does this close your issue #326?

Tests for #426 (arithmetic methods with CCDData and np.array)

---

ccdproc/tests/test_ccddata.py

An additional test for CCDData with meta and header in `__init__`.

Add test for CCDData with "meta" and "header".

---

ccdproc/ccddata.py
ccdproc/tests/test_ccddata.py

and removed dead code there.
But this is mostly adding additional tests.

Includes some tests for the compatibility StdDevUncertainty descriptor

---

CHANGES.rst
ccdproc/image_collection.py
ccdproc/tests/test_image_collection.py

Add keywords.deleter: Fixes #470

---

.travis.yml
ccdproc/tests/pytest_fixtures.py
ccdproc/tests/test_ccddata.py
ccdproc/tests/test_ccdproc.py
ccdproc/tests/test_combiner.py
ccdproc/tests/test_image_collection.py
setup.cfg

Fixes #446.
Let me know if I should include additional tests or remove some of these.

Activate pycodestyle test in travis (and fix some of the errors)

---

AUTHORS.rst
CHANGES.rst
ccdproc/image_collection.py
ccdproc/tests/test_image_collection.py

and refactored some of the internals
Fixes #487

Added changelog for glob* parameters in ImageFileCollection

---

CHANGES.rst
ccdproc/image_collection.py
ccdproc/tests/test_image_collection.py

Add __repr__ method to ImageFileCollection

---

AUTHORS.rst
CHANGES.rst
ccdproc/image_collection.py
ccdproc/tests/test_image_collection.py

**edit of the edit:**
**edit:** ~~Closes 423~~ Turns out that is not a MEF issue after all :)

Add multi-extension support

---

.travis.yml
appveyor.yml
ccdproc/tests/pytest_fixtures.py
ccdproc/tests/test_bitfield.py
ccdproc/tests/test_ccddata.py
ccdproc/tests/test_ccdmask.py
ccdproc/tests/test_ccdproc.py
ccdproc/tests/test_ccdproc_logging.py
ccdproc/tests/test_combiner.py
ccdproc/tests/test_cosmicray.py
ccdproc/tests/test_gain.py
ccdproc/tests/test_image_collection.py
ccdproc/tests/test_keyword.py
ccdproc/tests/test_rebin.py
ccdproc/utils/tests/test_slices.py

As the bundled version gets deprecation with v2.0

Using system pytest rather than astropy bundled

---

AUTHORS.rst
CHANGES.rst
ccdproc/combiner.py
ccdproc/tests/test_combiner.py

numpy.ndarray as an input for combine [#493]

---

MANIFEST.in

Adding LICENSE to manifest [ci skip]

---

README.rst

Minor fix - did this via the GitHub interface, so I think it made the branch on the upstream repo, sorry!

Update badges to SVG

---

ccdproc/utils/slices.py
docs/ccdproc/index.rst

add slices utilities to documentation

---

ccdproc/tests/test_image_collection.py

They are passing locally on my windows computer so I thought it might be worth testing if they really fail on AppVeyor.

Run ImageFileCollection tests on AppVeyor

---

CHANGES.rst
ccdproc/image_collection.py
ccdproc/tests/test_image_collection.py

This partially adresses #495.
This adds all new attributes `ext, globs` to the representation of `ImageFileCollection`.
TODO: Could needs some more tests :)

Added new attributes to ImageFileCollection representation

---

ccdproc/image_collection.py

It's a bit cleaner and probably a bit faster to use the dedicated function `np.ones` and `np.zeros` here.

Use np.ones or np.zeros instead of np.array([bool]*length)

---

ccdproc/image_collection.py

I'm not sure if that's actually an improvement but it has been bugging me every time I scan over that piece of code.

replace a multi-line ... if ... else ... construct with explicit branches

---

ccdproc/image_collection.py

There were three imports inside methods that I moved to the top of the file.

Put import statements from function scopes at the top of the file.

---

CHANGES.rst

These were added in #527 and #534 but I forgot to add them in these PRs.

Add some missing PR numbers in the changelog

---

CHANGES.rst
ccdproc/ccddata.py
ccdproc/tests/test_ccddata.py

Fixes #540 see also https://github.com/astropy/astropy/pull/6489

Fix combination of Headers when reading CCDData

---

CHANGES.rst
ccdproc/ccddata.py
ccdproc/tests/test_ccddata.py

For bugfixes:
See also https://github.com/astropy/astropy/pull/6500

Catch Exceptions when reading FITS file with malformed header

---

CHANGES.rst
ccdproc/image_collection.py
ccdproc/tests/test_image_collection.py

Add replace_ argument for files_filtered and _generator

---

CHANGES.rst
ccdproc/image_collection.py

Supercedes #545 which I messed up (without having a backup branch 😅 )

Fix RessourceWarnings in ImageFileCollection._generator

---

CHANGES.rst
ccdproc/image_collection.py
ccdproc/tests/test_image_collection.py

Allow "lower" method to be missing when filtering

---

ccdproc/ccddata.py
ccdproc/combiner.py
ccdproc/core.py
ccdproc/image_collection.py
ccdproc/log_meta.py
ccdproc/tests/test_bitfield.py
ccdproc/tests/test_ccddata.py
ccdproc/tests/test_ccdmask.py
ccdproc/tests/test_ccdproc.py
ccdproc/tests/test_ccdproc_logging.py
ccdproc/tests/test_combiner.py
ccdproc/tests/test_cosmicray.py
ccdproc/tests/test_gain.py
ccdproc/tests/test_image_collection.py
ccdproc/tests/test_keyword.py
ccdproc/tests/test_rebin.py
ccdproc/tests/test_wrapped_external_funcs.py

This was probably just a copy&paste mistake.

Remove inappropriate starting comments from files

---

ccdproc/tests/test_ccddata.py

Because astropys CCDData only trims the keywords if the keyword is longer than 8 **and** the value is longer than 72 chars it will throw VerifyWarnings when the CCDData contained a non-Header-meta (which shouldn't happen often - probably more often in our tests than in real use) and a ccdproc function was used whose long name is longer than 8 characters.

Catch warnings about too long keywords when using a normal dict as meta in tests

---

CHANGES.rst
ccdproc/image_collection.py
ccdproc/tests/test_image_collection.py

Deprecate info_file argument for ImageFileCollection

---

AUTHORS.rst
CHANGES.rst
ccdproc/core.py
ccdproc/tests/test_ccdproc.py

Update flat_correct to allow passing in a normalization.

---

.mailmap

That change was in a feature branch and I somewhat forgot to merge that into master before doing the release. 😓

Add Yoonsoo P. Bach to mailmap

---

ccdproc/core.py
ccdproc/extern/bitfield.py
docs/ccdproc/ccddata.rst

Fixes the failing NumPy dev doctests

Adapt for NumPy dev representation changes

---

.travis.yml

This should fix the remaining test that errored out.

Pin Pytest version for astropy 1.3 travis build

---

docs/ccdproc/reduction_examples.rst

Add mont4k pipeline to examples.

---

ccdproc/image_collection.py

Actually fix #699 by removing the offending import line

---

.travis.yml

CI: Remove allow_failure from travis

---

ccdproc/extern/bitfield.py
ccdproc/log_meta.py
ccdproc/tests/test_ccdmask.py
ccdproc/tests/test_ccdproc.py
ccdproc/tests/test_cosmicray.py
ccdproc/tests/test_image_collection.py

Addressed some test warnings that come up while testing. Also made comments consistent along the way.
Thanks!

Reduce test warnings

---

CHANGES.rst
ccdproc/combiner.py
ccdproc/tests/test_combiner.py
docs/image_combination.rst
setup.cfg

Document use of `ImageFileCollection` with `Combiner`/`combine`

---

ccdproc/core.py

Not sure this really warrants a pull request, but....fixes #779

Be more explicit about the removal of rebin

---

setup.cfg

Forgot to change this in setup...

Increase minimum supported astroscrappy version

---

AUTHORS.rst
ccdproc/image_collection.py

Fixed the return type documentation for the hdus method.
Closes #792

Fix documentation for hdus

---

.git-blame-ignore-revs
ccdproc/__init__.py
ccdproc/_astropy_init.py
ccdproc/ccddata.py
ccdproc/combiner.py
ccdproc/conftest.py
ccdproc/core.py
ccdproc/image_collection.py
ccdproc/log_meta.py
ccdproc/tests/make_mef.py
ccdproc/tests/pytest_fixtures.py
ccdproc/tests/run_for_memory_profile.py
ccdproc/tests/run_with_file_number_limit.py
ccdproc/tests/test_bitfield.py
ccdproc/tests/test_ccdmask.py
ccdproc/tests/test_ccdproc.py
ccdproc/tests/test_ccdproc_logging.py
ccdproc/tests/test_combine_open_files.py
ccdproc/tests/test_combiner.py
ccdproc/tests/test_cosmicray.py
ccdproc/tests/test_gain.py
ccdproc/tests/test_image_collection.py
ccdproc/tests/test_keyword.py
ccdproc/tests/test_memory_use.py
ccdproc/tests/test_rebin.py
ccdproc/tests/test_wrapped_external_funcs.py
ccdproc/utils/sample_directory.py
ccdproc/utils/slices.py
ccdproc/utils/tests/test_slices.py
pyproject.toml

This applies black to the codebase

Black format codebase

---

.pre-commit-config.yaml
pyproject.toml

This will implement a fairly minimal set of pre-commit rules for now.

Add pre-commit and auto-formatting with black

---

pyproject.toml

Address a few minor issues identified by scientific python repo checker

---

.github/workflows/ci_tests.yml

MNT: Use hash for Action workflow versions and update if needed

---

.github/workflows/ci_tests.yml

Fix error in test case

---

.pre-commit-config.yaml

Update ruff version

---

AUTHORS.rst
CHANGES.rst
ccdproc/combiner.py
ccdproc/core.py

This addresses #849 .  It also makes some adjustments to the flat-field correction function to avoid some divide by zero errors and a minor change in the unit book-keeping.
For bugfixes:

Minor masking and flat-field updates

---

.github/workflows/ci_tests.yml
ccdproc/__init__.py

TST: Fetch tags for dynamic version
