- .travis.yml
- docs/rtd-pip-requirements
Change travis back to using astropy stable and RTD to using 1.0 or higher rather than a release candidate.
> Back to usual configuration now that astropy 1.0 is out

- CHANGES.rst
- ccdproc/ccddata.py
- ccdproc/tests/test_ccddata.py
- docs/ccdproc/ccddata.rst
If hdu is set to zero and there is no data in the primary header, it will then search for the first extension with data.
closes #173
> Hdu default

- CHANGES.rst
- ccdproc/ccddata.py
- ccdproc/tests/test_ccddata.py
- ccdproc/tests/test_ccdproc.py
- docs/ccdproc/ccddata.rst
This really ended up being a couple of changes:
+ Create a WCS object if the necessary information is present when creating a `CCDData` object from a FITS file.
+ If there is a WCS attribute then write that attribute's information into the HDU created with `to_hdu`.
I also added a test that slicing properly affects the WCS attribute.
There is still one potential issue here -- the header could have WCS information different than the WCS attribute if the `CCDData` object is created with a FITS header as the metadata and that header would get partially overwritten (but maybe not completely if the WCS in the header is a different projection/has distortions and the WCS attribute doesn''t).
> Add proper handling of WCS

- ah_bootstrap.py
This is an update of astropy-helpers to fix the most recent version.   I've initiated this due to the install of ccdproc when it is a dependency in another package to fail when building on readthedocs due to VersionConflicts in the astropy_helpers.   
I think this is related to https://github.com/astropy/astropy-helpers/pull/144 but I'm not 100% sure.   However, it is probably best to have the lastest version of helpers in ccdproc anyway.  
This will require a patch of ccdproc to release to ultimately fix this bug I think though.
Also a note about updating to the most recent version of astropy_helpers should be added to the release documents.
> Updated astropy-helpers to release-1.0.1

- docs/ccdproc/index.rst
This just removes the warning from the docs in ccdproc.  Right now the warning is pretty scary, and I think it probably prevents anyone from using it for real work.  I'm speculating that it's from a while back and the situation is not quite so dire,  @crawfordsm and @mwcraig?
If you think at least the "API might change" should still be in there, I could put that back in.  I think "you might have to make some future changes to keep it working" is much less scary than "this might be totally wrong" (which is the current tone).
> Remove generic warning for using ccdproc

- ccdproc/combiner.py
This is to address and close #216 and #222.
``scale_func`` may benefit from a rename, or changed functionality.
> Fixing unused parameters for average_combine() 

- .travis.yml
- ccdproc/ccddata.py
- ccdproc/tests/test_ccddata.py
Some keywords (blank, comment, history) can have multiple values. Using `iteritems` properly iterates over those cases.
Closes #228
> Copy WCS header in a way that properly handles list-like keywords

- ccdproc/ccddata.py
- ccdproc/combiner.py
- ccdproc/core.py
- ccdproc/log_meta.py
- docs/ccdproc/index.rst
- docs/ccdproc/reduction_toolbox.rst
- docs/conf.py
- docs/nitpick-exceptions
There are still 3 failing links, not sure how to fix them. They came in the inheritance of ``NDDataArray``, and I think they should have been resolved automatically as ``astropy.nddata.NDIOMixin``, etc just as ``NDDataArray`` did. As a workaround I can put them in the ``nitpick-exceptions``, but I believe there  is a better solution out there.
cc @astrofrog as he may know the trick here.  
```
/Users/bsipocz/munka/devel/ccdproc/docs/ccdproc/index.rst:156: WARNING: py:class reference target not found: astropy.nddata.mixins.ndio.NDIOMixin
/Users/bsipocz/munka/devel/ccdproc/docs/ccdproc/index.rst:156: WARNING: py:class reference target not found: astropy.nddata.mixins.ndslicing.NDSlicingMixin
/Users/bsipocz/munka/devel/ccdproc/docs/ccdproc/index.rst:156: WARNING: py:class reference target …
```
> Enabling docs nitpicky mode

- ccdproc/tests/test_combiner.py
I think this was a typo. The test for median_combine was previously calling average_combine method.
> Minor typo fix: Calling median_combine inside median test

- .travis.yml
- ccdproc/ccddata.py
- ccdproc/tests/test_ccdproc.py
Update to ccdproc to take account of issues created with the merging into astorpy 1.05 of astropy/astropy#4130  and #241.   CCDData should still be backward compatible with earlier versions of astropy, but any code that uses CCDData(data=...) format will be broken.
> Astropy v1.05

- .travis.yml
- ccdproc/conftest.py
Miniconda's default prefix changed recently causing all travis builds failing.
> Updating .travis to reflect recent miniconda changes

- ccdproc/image_collection.py
- ccdproc/tests/test_image_collection.py
- docs/ccdproc/image_management.rst
In addition, this clarifies the docstring a bit to explain how column order is determined.
The only case in which it is determined by the order of the keywords passed to the constructor is when the wildcard `*` is *not* used.
Otherwise the column order is the order in which the keywords appear in the first FITS file opened.
> Ensure column order in ImageFileCollection matches the order of keywords in constructor

- docs/ccdproc/image_management.rst
I tried to make the naming a little more uniform. Sometimes it was `I band images` sometimes it was "I-band light", `I-band light` or `'I' band light`.
> Fix typos and unify wording in image_management

- .travis.yml
- appveyor.yml
- ccdproc/tests/test_image_collection.py
- docs/ccdproc/ccddata.rst
This is to address and close #259.
I've also added ccdproc as a project on appveyor itself for astropy.
> Adding appveyor testing and opting in ci-helpers

- CHANGES.rst
- ccdproc/image_collection.py
- ccdproc/tests/test_image_collection.py
This introduces a new keyword "include_path".
Note that this keyword can never clash with any fits header keyword, because
those are limited to 8 characters.
> Include an option to return the full path in ImageFileCollection.files_filtered

- CHANGES.rst
- ccdproc/image_collection.py
- ccdproc/tests/test_image_collection.py
- docs/ccdproc/image_management.rst
This uses the underlying table structure to do that sort, it also updates
the separate self._files accordingly.
This method allows me to set a the order in which the files are processed,
e.g. I can iterate over all files and make plots sorted alphabetically by
'OBJECT' or by 'OBS-TIME' or 'FILTER'.
A related change is to sort the file list when reading files from a
directory. This sorting is alphabetical, if the user does not like it
they can always use the new 'sort' function later.
This change makes the order of files that are read in reproducible, which is useful
when the iterators are used to make plots of each file - I want the same order
when I re-run my script.
(Without this change the order of files seems to change randomly at times.)
> Add a 'sort' method to ImageFileCollection

- ccdproc/ccddata.py
- ccdproc/tests/test_ccddata.py
Updated how the header is read in if the data is not in the primary extension.  When reading in data and then writing it out, if the data is in the first extension rather than the primary extension all of the information in the primary extension is lost.
This fixes that problem by combining the header in the primary extension and the extension in which the data first appears in.  This data is then written out as a single header when the CCDData object is written out.
> Updated how the header is read in if the data is

- CHANGES.rst
- ccdproc/core.py
- ccdproc/tests/test_ccdproc.py
If the overscan axis is explicitly set to `None` in
`subtract_overscan`, the overscan direction is determined from the
shape of the overscan section, set the shortest dimension. (In case of
a square overscan, the default of 1 is picked.)
This can be convenient in cases where `fits_section` is used with an
(unknown) input string (for example, from an image's BIASSEC header
keyword): the user can let the function determine the appropriate
axis.
> Add option to automatically determine the overscan axis

- CHANGES.rst
- ccdproc/utils/slices.py
- ccdproc/utils/tests/test_slices.py
This handles FITS sections with
- wildcards: '[*]'
- negative wildcards: `[-*]`
- inverted range specification: `[20:10]`
- step size specification for each of the above cases:
`[*:2]`, `[-*:2]` or `[20:10:2]`
> Extend handling of FITS section syntax for slicing

- ccdproc/core.py
From a discussion in https://github.com/astropy/ccdproc/issues/281#issuecomment-171936763.
I think it would be best to rely on ``CCDData.__getdata__`` instead of trying to the same inside the ``trim_image`` function itself.
> trim_image calls CCDData slicing even if fits_section is given.

- ccdproc/ccddata.py
- ccdproc/tests/test_ccddata.py
For arithmetic between two CCDData objects, this will ignore any difference between WCS unless compare_wcs is set to True
> Ignore wcs

- .travis.yml
- ccdproc/conftest.py
- docs/ccdproc/install.rst
This is to speed up travis a bit, and to mention the astroscrappy dependency in the docs.
Note that it's failing as no conda packages are available for older python/numpy versions. Waiting for the resolution of https://github.com/astropy/conda-builder-affiliated/issues/91 and then I'll either push another commit to install it from pip in those cases or there will be conda packages available.
> Astroscrappy cleanup

- docs/ccdproc/index.rst
Removed discussion of Keyword class in Getting Started section of documentation (index.rst).
> Issue #235. Removed discussion of Keyword class in Getting Started section.

- ccdproc/ccddata.py
fixes #304 
I'm not sure if that's the best way but it at least makes the documentation of ``CCDData.read()`` and ``CCDData.write`` accessible.
> include read and write method documentation to CCDData [skip ci]

- ccdproc/ccddata.py
- ccdproc/combiner.py
- ccdproc/core.py
- ccdproc/tests/test_ccddata.py
- ccdproc/tests/test_combiner.py
Added a default uncertainty function in average_combine of combiner.py so that an uncertainty function can be passed optionally. This closes part of issue #224. As for the other part would it be preferable to let the default uncertainty function in median_combine be median_absolute_deviation and then use a conditional to multiply by the factor of 1.4826 if the uncertainty function is the default using something like:  
def median_combine(self, median_func=ma.median, scale_to=None, uncertainty_func=median_absolute_deviation):
. . . 
if uncertainty_func is median_absolute_deviation:
uncertainty_func *= 1.4826
or would it be better to define a function for median_absolute_deviation that does this multiplication so that uncertainty can simply be assigned the default or optionally passed …
> Added default uncertainty function in average_combine of combiner.py

- CHANGES.rst
- ccdproc/log_meta.py
The ``add_keyword`` parameter now uses a more explicit default value
of ``True``. Setting it to any falsely value (``False``, ``None``,
``""`` etc.) disables logging. [#310]
> Set default for add_keyword parameter to True

- CHANGES.rst
- ccdproc/combiner.py
- ccdproc/tests/test_combiner.py
Fixes #309 
Please review this carefully.
Some (remaining) open issues:
- Since you did not pass ``ddof`` to ``np.ma.std`` I didn't correct for finite populations either and just divided by ``np.sqrt(valid_pixel)``. This might not be exactly correct but I'm not too sure about statistics. The downside with such an finite population correction is also that the number of valid pixel could be 0 and then subtracting 1 and taking the square root ... not good.
- both combiners ignore scaling and weighting for the uncertainty computation.
- median combine ignores the masked values (probably because ``median_absolute_deviation`` cannot handle these. Therefore I corrected just with the whole number of pixel because these are used for uncertainty computation. It's inconsistent but I don't have time …
> Scale uncertainty with the number of combined pixel during combination.

- ccdproc/image_collection.py
Without the slash, the filename is appended directly to the path string.
E.g. for the path returned by self._location: `C:\\Users\\EP_Guy\\images`, and an image file `M42_001.fits`, `filtered_files` returns `C:\\Users\\EP_Guy\\imagesM42_001.fits`
> Add slash so full path is correctly returned

- ccdproc/tests/test_image_collection.py
I checked locally that this test failed before #325 but passes after it is merged. Assuming the build passes I'll merge.
> Test for whether path is properly constructed in files_filtered

- ccdproc/image_collection.py
I tried running image_collection on my data but the 3rd fits extension is not recognised. .fts is also used as well as .fits and .fit. Seems to be a simple fix. I could also just rename my files but this should make the extension grabbing complete.
> adding .fts support to image_collection.py

- ccdproc/ccddata.py
See #343 
`CCDData.meta.setter` will initialize an empty `collections.OrderedDict` in case the new value is `None`. 
This is because `NDData` implements `meta`-checks as part of the setter itself (astropy >= 1.2) instead of during `__init__` (astropy < 1.2).
> Fixes #343 by defaulting to OrderedDict in CCDData.meta.setter

- ccdproc/ccddata.py
- ccdproc/combiner.py
- ccdproc/core.py
- ccdproc/image_collection.py
- ccdproc/log_meta.py
- ccdproc/tests/test_image_collection.py
- docs/ccdproc/ccddata.rst
I've fixed some formatting issues, deleted some newlines in docstrings and included some points.
Closes #338
> Fixed some formatting problems and included a lot of points [skip ci]

- CHANGES.rst
- ccdproc/core.py
This PR fixes #347 by changing default saturation level to 65535 electrons. 65535 is the more common saturation level on CCDs as it is the maximum unsigned 16 bit value (2^16 - 1).
> Change lacosmic saturation level default to 65535

- ccdproc/ccddata.py
Astropy 1.2 will have numerous changes for NDData and some tests are failing here because of it.
This PR fixes the failure and also fixes all failures related to the fix. Unfortunatly these failures are somewhat entangled and it's not possible to seperate them easily.
The cyclic reference between `CCDData` and `uncertainty` results in a memory leak where neither of both can be deallocated. So the parent_nddata must save the uncertainty as weakref. A descriptor is just a `property` in this case: `__get__` is the `getter` and `__set__` the `setter`.
This is an ugly monkey-patch... and it only works for those `StdDevUncertainties` that are created after `ccdproc` is imported... But I couldn't think of a way to fix the memory leak without requiring astropy 1.2. If your next release would …
> Astropy release changes

- CHANGES.rst
- ccdproc/combiner.py
- ccdproc/tests/test_combiner.py
Fixes #351, https://github.com/mwcraig/reducer/issues/117
I think just casting the uncertainty to a plain numpy array after the combination is enough to fix the problem. The uncertainty is created by applying a ``numpy.ma.ufunc`` on the **data** so any masked pixels are already masked in the data so there should be no need to keep track of an identical mask on the uncertainty.
FYI: 1 minute to fix the Bug, 20 to figure out how I could make the tests pass ... ugly fixtures and tmpfiles.
> cast uncertainty to plain numpy array after combining.

- ccdproc/core.py
The axis should be passed to stats.median_absolute_deviation in order to behave as explained in the docstring.
> Use axis when calculating median absolute deviation

- ccdproc/combiner.py
- ccdproc/tests/test_combiner.py
- docs/ccdproc/image_combination.rst
This is a quick attempt at adding the rejection method described in issue #356 
This rejection method needs a better name.  There could be confusion due to people coming from the IRAF "minmax" terminology.  I've put in a cumbersome name of iraf_minmax_clipping for now.
Note that this method changes the combiner object's self.data_arr in place by doing a numpy sort.  Is this a problem?  Will it interact badly with other parts of ccdproc?
Edit: closes #356
> Add iraf_minmax_clipping method to give IRAF-like minmax clipping.

- CHANGES.rst
- ccdproc/core.py
- ccdproc/tests/test_ccdproc.py
- docs/ccdproc/reduction_toolbox.rst
This pull request address #361 in two ways:
1. The documentation for `ccd_process` now clearly states what the expected units of the calibration images are.
2. I've implement, for `subtract_bias`, a more explicit check for a units mismatch and raise a `UnitsError` instead of a `ValueError` in that case.
The error message looks like this: `UnitsError: Unit adu of the uncalibrated image do not match unit m of the calibration image`
@mrkite92 -- would this have been clearer in your case?
@crawfordsm -- if you like this approach, let me know and I'll do it for subtract dark also.
> Address units expected for calibration images in ccd_process

- ccdproc/combiner.py
The current error message says the _mask_ must be a numpy array when setting the _weights_. This PR should fix this.
> Fix error message in weights setter.

- docs/ccdproc/image_combination.rst
This is some residual from a previous commit: https://github.com/astropy/ccdproc/commit/9e95902a0e54d1ba4ce0f3356d0aaebb8691ea11
> removes a lonely a in the narrative docs

- ccdproc/image_collection.py
The helper function has an argument ``n_prev`` but used ``n_previous``. This doesn't cause any bugs because the "not local" variable ``n_previous`` holds the same value. But I've renamed the function argument to ``n_previous`` (and added ``missing_marker``) so Python doesn't need to search in nonlocal scopes.
The third small change here was that the helper function now immediatly converts the key to lower-case so ``key.lower()`` is only called once even if the key wasn't present in the ``tbl_dict``.
> Use local scope variables in the helper function in FileCollection._dict_from_fits_header

- AUTHORS.rst
- CHANGES.rst
I'm letting the CI run since the changelog and authors are integrating into the docs.
> Update changelog/authors in preparation for 1.1 release

- .travis.yml
- appveyor.yml
Conda channels now need to be explicitly listed, ci-helpers won't add astropy and astropy-ci-extras by default in the future astropy/ci-helpers#128.
> Adding conda channels to CI files

- CHANGES.rst
- ccdproc/combiner.py
- ccdproc/tests/test_combiner.py
Fixes #391 
This PR adds a ``dtype`` parameter which is passed to ``Combiner``.
This fixes two Bugs:
- if the dtype of the first ccd passed to `combine` isn't ``float64`` the result was downcast to the dtype of the first ccd.
- in that case also the memory consumption calculation was wrong because `Combiner` used `float64` while the calculation assumed the `dtype` to be the same as the one of the first ccd.
And also allows to optionally reduce the memory consumption by simple using a `dtype`.
> add dtype argument to combine-function.

- ccdproc/combiner.py
Closes #390 
The reason why the exception in #390 occured was because for some reason (haven't investigated it) it wasn't possible to create a HIERARCH card for the compressed image. For normal calls to `ccdproc.core` functions one could disable logging by setting the `add_keywords` parameter but that's currently not possible for `ccdproc.combine`. 
However it's just not necessary to add the logging message for the trimming to Header because the trimming is not really done, it's just there to avoid using too much memory.
So instead of trimming the ccddata object it's just sliced in combine. This fixes the error locally but I haven't been able to create a test case for this.
> replace the trim_image call in combine with direct slicing to avoid logging.

- CHANGES.rst
- ccdproc/core.py
- ccdproc/tests/test_ccdproc.py
I identified one place where the `meta` could be lost when calling `ccd_process` (#401).
Maybe @crawfordsm or @RogueAstro could confirm if this PR fixes the issue.
Closes #401
> Copy Meta in ccd_process when "subtract_bias" image

- CHANGES.rst
- ccdproc/image_collection.py
- ccdproc/tests/test_image_collection.py
Implements #374.
I added an optional parameter named ``filenames``  which should contain the names of the FITS files in the directory which should be added to the collection. If ``filenames`` is ``None`` and ``location`` is not, then all FITS files in ``location`` are added to the collection.
Appreciate any feedback on this.
> Allow ImageFileCollections to take a list of file names

- docs/rtd-pip-requirements
I don't know if that would fix the failing readthedocs builds (http://readthedocs.org/projects/ccdproc/builds/) but I did forget to add it there.
> add scikit-image to rtd-requirements

- docs/index.rst
- docs/license.rst
I think somewhere in the docs we should mention the license
> Adding licence to the docs

- CHANGES.rst
- ccdproc/ccddata.py
Fixes #399, Fixes #359
I wasn't sure if a COMMENT card would be better, but that wouldn't be backwards compatible, so this just explicitly creates HIERARCH cards to avoid the annoying warnings.
```
>>> import ccdproc
>>> import numpy as np
>>> from astropy.io import fits
>>> ccd = ccdproc.CCDData(np.ones((5, 5)), meta=fits.Header(), unit='adu')
>>> ccd2 = ccdproc.subtract_bias(ccd, ccd)  # no warnings anymore
>>> ccd2.meta
HIERARCH SUBTRACT_BIAS = 'subbias ' / Shortened name for ccdproc command        
SUBBIAS = 'ccd=<CCDData>, master=<CCDData>'
```
> Explicitly create HIERARCH cards in CCDData._insert_in_metadata_fits_safe

- ccdproc/core.py
For bugfixes:
Not sure which boxes to tick for this PR.
The two exception messages are clearly wrong because the ifs, the docstring (and the functions) state that it must be None or CCDData.
> Correct two exception messages in ccdprocess

- .travis.yml
- ccdproc/tests/test_ccdproc.py
This removes some of the tests in `.travis.yml`. I think I've incorporated all of them in the remaining tests.
It also adds one more test for numpy-dev (which will fail 😄 )
This reduces the build-time from 35m -> 25m.
> Travis matrix changes

- ccdproc/core.py
- ccdproc/tests/test_ccdproc.py
For bugfixes:
When comparing the results to the support_nddata decorator I noticed that these functions did not copy the `meta` property. This PR fixes this and includes a regression test.
> Copy meta in block_x functions

- docs/index.rst
This shows one more nesting of the docs-tree on the main documentation page.
I think this makes it much easier to access the relevant "tutorials":
Currently it's: http://ccdproc.readthedocs.io/en/latest/#documentation
> show tutorials on the main documentation page

- ccdproc/ccddata.py
- ccdproc/combiner.py
- ccdproc/image_collection.py
- ccdproc/log_meta.py
This PR mostly fixes static PEP8 linting warnings for lines that are too long.
I also changed the "Notes" section from the combiner to an "Examples" section (because it, well, just contained an example) and moved parts of the "Combiner.clip_extrema" documentation into a "Notes" section.
In `log_to_metadata` I combined handling positional and keyword arguments into one iteration instead of doing both seperatly and combining them later, functionality is the same just without the repetition.
> PEP 8 changes and minor change in logger

- ccdproc/ccddata.py
I've added no regression test (because `hdu_flags=None` is the default and therefore already checked in several tests) and I added no changelog entry because it shouldn't change any behaviour.
The reason this fails is because `None in HDUList` is not allowed anymore in `astropy.io.fits` but `hdu_mask`, `hdu_uncertainty` and `hdu_flags` are allowed to be `None`.
I reported the issue upstream: https://github.com/astropy/astropy/issues/5583 but I think we should change it even if it's not fixed upstream.
> Only check for HDUs if they are not None (fits reader)

- ccdproc/utils/slices.py
This changes a link to the `string` module to a code-formatted text.
> Small docstring fix

- .travis.yml
- ccdproc/ccddata.py
This PR changes manual `LooseVersion` checks in `CCDData` with `astropy.utils.minversion` (more convenience) and adds two new 1.3 features:
- `astropy.io.fits.is_fits` was changed to also accept `fts` so we don't need the custom function anymore
- `astropy.io.registry` can now delay documentation updates when registering reader/writer for the registry. This may reduce the import time _slightly_.
> Using minversion for version checks and include some new 1.3 features

- ccdproc/tests/test_ccddata.py
With the recent change in #426 I thought it would be a good idea to test these code paths a bit more. Just so that failures won't go unnoticed.
> Add tests for wcs_compare in CCDData arithmetic

- CHANGES.rst
- ccdproc/ccddata.py
- ccdproc/tests/test_ccddata.py
Removing the ability to set the unit of `CCDData` to None.    This is to make it consistent with the behavior when initiating `CCDData`.
> changed unit setter 

- .travis.yml
- appveyor.yml
Probably we need to wait a bit more until all the dependencies become available on python 3.6.
> Adding python 3.6 to CI builds

- ccdproc/image_collection.py
This is simply a refactor of the keywords setter in ImageFileCollection.
It saves some unnecessary list (2 before, 1 in this PR) / set (3 before, 1 in this PR) casts.
> removed several list->set or set->list operations in imagefilecollection.keywords setter

- CHANGES.rst
- ccdproc/image_collection.py
- ccdproc/tests/test_image_collection.py
Checklist:
This implements option 3 from https://github.com/astropy/ccdproc/issues/464#issuecomment-285733207:
> Ignore these duplicate entries with a warning.
I haven't implemented a check if these entries are equal but the warning includes a message about the file and the ignored keyword value pair. Is that enough information?
@janga1997 I hope you don't mind that I made another pull request. I started reviewing #465 but that did not fix the bug and introduced a lot of new bugs.
> Handle duplicated header-keywords in ImageFileCollection

- appveyor.yml
With the 1.3.1 astropy release the AppVeyor test should pass for 3.6 and numpy 1.12
Fixes #472
> Remove conda-forge channel from AppVeyor

- ccdproc/image_collection.py
- ccdproc/tests/test_image_collection.py
- docs/ccdproc/image_management.rst
I've been using `ccdproc` quite a bit lately for doing spectroscopic data reduction. I've found that I often want to be able to select subsets of my data based on filename pattern matching to test out certain pieces of the reduction pipeline, so I had implemented something like the features in this PR locally on a subclass of `ImageFileCollection`. If you like it, I'll add a changelog entry.
> Add Unix-style filename inclusion/exclusion to imagecollection

- ccdproc/tests/test_ccdproc.py
- ccdproc/tests/test_image_collection.py
Actually I don't know why these `print`s were in these tests. `pytest` actually does a great job at displaying differences so it seems they were used to create the tests but should've been removed afterwards.
Correct me if I'm wrong.
> Remove prints in tests

- ccdproc/image_collection.py
This also fixes the target for the `hdus` generator `HDU`->`HDUList`.
> Use links in the "returns" section of the ImageFileCollection generator methods

- CHANGES.rst
- ccdproc/image_collection.py
- ccdproc/tests/test_image_collection.py
The attribute is marked as deprecated in the docstring and it was since the `ImageFileCollection` was implemented in #217 . I had to change quite a lot to actually remove it.
> remove deprecated summary_info propery of ImageFileCollection

- CHANGES.rst
- ccdproc/core.py
- ccdproc/tests/test_ccdproc.py
This Fixes #490 and adds the option to include ``gain_corrected``.  If set to False, the calibrations files will be assumed to be un-gained corrected and the gain correction will only occur after those corrections are applied to the gain correction
Default value for ``gain_corrected`` is True, which is inline with backward compatibility
> gain_corrected in ccd_process

- ccdproc/tests/pytest_fixtures.py
This fixes a failure with astropy dev because we still imported the (now removed: https://github.com/astropy/astropy/pull/6164) `astropy.utils.compat.gzip` module.
> fix unneeded compatibility import

- AUTHORS.rst
- CHANGES.rst
- ccdproc/combiner.py
- ccdproc/tests/test_combiner.py
> Added sum combiner (#500)

- .travis.yml
While looking into a failure with the sphinx build I noticed that we use the deprecated `build_sphinx` command there: https://travis-ci.org/astropy/ccdproc/jobs/255026568#L621
> Use build_docs instead of the deprecated build_sphinx in travis

- ccdproc/core.py
Some parameter descriptions were missing the whitespace before the colon.
> Fix the docstring of the ccdmask function

- ccdproc/tests/test_image_collection.py
This imports `ImageFileCollection` directly in the test suite and for a few functions I removed the `tmpdir` fixture.
Overall this makes the test code just a bit more compact.
> Minor cleanup in imagefilecollection tests

- .travis.yml
If we want to support the last astropy LTS and astropy 1.3 for the next release we should probably test against these.
> Test against astropy 1.0 and 1.3

- .travis.yml
NumPy 1.13 has been released for a few weeks so don't test against NumPy 1.12. 
In case we want to drop NumPy 1.10 support (or at least don't test against it) it could also be shuffled:
- Python 3.4 + NumPy 1.11 (previously NumPy 1.10)
- Python 3.5 + NumPy 1.12 (previously NumPy 1.11)
> Include a numpy 1.12 test in travis

- ccdproc/image_collection.py
- ccdproc/tests/test_image_collection.py
Fixes: #516 
This only affects the development branch so it shouldn't need a changelog.
> Make glob attributes of ImageFileCollection readonly

- CHANGES.rst
- ccdproc/image_collection.py
- ccdproc/tests/test_image_collection.py
It might make sense to think how one could use ``overwrite=True`` with the `ccds` generator in `ImageFileCollection` but given that there could be multiple extensions involved (which the generator doesn't know about) and because `CCDData` doesn't support many in-place operations that won't be straight-forward. So I'm not sure if #453 can be closed afterwards.
However currently the parameter is silently ignored without warning or exception which this PR fixes by raising a `NotImplementedError`.
> Raise an exception instead of silently ignoring overwrite in ccd generator

- ccdproc/image_collection.py
At this place the dictionary isn't needed and a simple loop can also avoid the double `.lower()` call.
> Replace a dict-comprehension with a loop in ImageFileCollection

- CHANGES.rst
- ccdproc/image_collection.py
- ccdproc/tests/test_image_collection.py
Just found out by coincidence that `sort` without argument always throws a `ValueError` so it's probably better to make the `keys` argument mandatory.
> Make key argument for ImageFileCollection.sort mandatory

- ccdproc/image_collection.py
Setters actually don't need a default value because that would only be useful if one accesses the `fset` method of the property instance directly.
> Remove unnecessary default value for keyword property setter.

- ccdproc/image_collection.py
Almost immediately the argument will be passed to `list` which would throw a `TypeError` because `None` isn't iterable.
Given that it's a private method I didn't add a test and changelog.
> Make "header_keywords" argument for "_fits_summary" method mandatory

- ccdproc/tests/test_image_collection.py
Seems like I forgot them in #486
> Remove deprecated summary_info attribute access on ImageFileCollection from tests

- ccdproc/tests/test_ccdproc.py
This is mostly because Warnings are now shown in the pytest runner and I'm looking for a way to reduce them, fixing the trivial ones (like this one) first.
> Catch the warnings from block* functions in the tests.

- CHANGES.rst
- ccdproc/ccddata.py
- ccdproc/combiner.py
- ccdproc/core.py
- ccdproc/image_collection.py
- ccdproc/log_meta.py
- ccdproc/tests/test_ccddata.py
- ccdproc/tests/test_ccdproc_logging.py
- docs/ccdproc/ccddata.rst
- docs/ccdproc/index.rst
- docs/ccdproc/reduction_toolbox.rst
Fixes #510  (and maybe #232)
I tried to make minimal changes but a few tests had to be rewritten and the logging system now works a bit differently.
I included some comments about the need for the change but if some change seems "weird" please mention it so I can include a comment why that's needed.
> Use CCDData from astropy.nddata if astropy version >= 2.0

- ccdproc/tests/test_ccddata.py
Will still fail the astropy-dev test but only until https://github.com/astropy/astropy/pull/6489 is merged.
> Fix test failures because two previous PRs interfered with each other

- ccdproc/tests/test_ccddata.py
I found the warning in a test log against NumPy master: https://travis-ci.org/astropy/ccdproc/jobs/270021313#L787
The correct form is to use `np.floating` as second argument.
> Fix a FutureWarning from NumPy regarding non-dtype argument for issubdtype

- ccdproc/tests/test_ccddata.py
The fix hasn't made it in 2.0.2 so the test needs an update so we don't fail all tests against astropy 2.0.x
> Change minversion to 2.0.3 for a CCDData test

- ccdproc/combiner.py
- docs/ccdproc/ccddata.rst
Based on https://github.com/astropy/astropy/pull/6090. Let's just hope it's backported and the astropy 2.0.3 is released before NumPy 1.14 is, otherwise the `+FLOAT_CMP` won't do the "correct thing".
> Fix failures against numpy dev

- ccdproc/image_collection.py
- ccdproc/tests/test_image_collection.py
And it adds quotations around the keyword name in the warnings message
> Catch the warnings message in duplicated keyword test

- ccdproc/tests/test_combiner.py
Several tests were using `np.median` on masked data. Some of them should use `np.ma.median` others were better off using `np.median` on the `data` directly.
> Use np.ma.median in the Combiner tests

- ccdproc/tests/test_gain.py
Currently the tests raise warnings because several values are negative.
> Use absolute of data in gain tests so the sqrt does not warn

- ccdproc/tests/test_ccddata.py
Currently that test creates an `(100, 100, 100, 100)` random array (because of the `s*ccd_data.shape`) which is somewhat unnecessarily slow.
> Speeding up an unnecessarily slow test

- ccdproc/combiner.py
- ccdproc/core.py
The parameter name was different from the name in the parameter docstring section.
> Correct some incorrect parameter names and fixed typos

- CHANGES.rst
- ccdproc/ccddata.py
- ccdproc/tests/test_ccddata.py
This is so we have the same behavior as astropy 2.0
The test is different and I'm not sure it's completely correct.
> Remove wcs-related header-items when reading CCDData from file

- ccdproc/tests/test_ccdproc.py
https://github.com/astropy/astropy/pull/6590 caused two deprecation warnings in our test suite but not related to actual code, just inside the test.
The reason is that composite-units like `u.electron / u.adu` create Quantities and casting them to `bool` currently raises a deprecation but it will be an Error in the future.
> Fix deprecations in tests with astropy development version

- ccdproc/tests/test_image_collection.py
It seems a bit odd that these are also emitted if one loads from an info-file but technically it's correct to emit them (and informational for the user) because the info-file doesn't populate the files attribute.
> Catch warnings if no files are in the collection

- CHANGES.rst
- ccdproc/image_collection.py
- ccdproc/tests/test_image_collection.py
The `replace_` argument was basically a good idea but as #559 and #557 show whitespaces are not the only problematic character. ``-`` is quite frequently used and sometimes even ``.``. Other invalid characters for keyword arguments are quite rare.
However it might be better to just document the workaround (passing in an unpacked dictionary) than actually inventing a functionality that tries to cover these cases in an easy to use way.
If we make `replace_` a dictionary for characters to translate that will be very awkward to use (because you could end up inventing different placeholders for different characters) and when you're passing in a dictionary already one might as well pass in the dictionary containing the key-value pairs.
Note that `replace_` hasn't been released yet so this …
> Remove replace_ argument for files_filtered again

- pytest.ini
- setup.cfg
We currently use `pytest.ini` **and** the pytest section in `setup.cfg`. This PR removes the pytest.ini and puts the stuff in the setup.cfg.
Not sure if that makes sense though.
> Remove pytest.ini in favor of setup.cfg

- setup.cfg
Fixes #590 
Not sure if this is a general problem but it's not really necessary to use unicodes there so we might as well remove it.
> Replace unicode quotation marks in setup.cfg

- ccdproc/image_collection.py
The parameter name is `extensions` not `extension`.
> Wrong parameter name in docstring

- CHANGES.rst
- ccdproc/image_collection.py
This speeds up several places where a Python iteration over a numpy.ndarray or astropy.table.Column is made. It will require slightly more memory but that is probably not noticeable for ImageFileCollections with less than several thousand files and my assumption is that ImageFileCollection will be very slow (probably unusable slow) for that many files anyway.
> Speed up ImageFileCollection by using tolist more often

- CHANGES.rst
- ccdproc/combiner.py
- ccdproc/tests/test_combiner.py
For bugfixes:
The same code as #608 now gives correct answer:
```
-- median:
[[ 4.5  3.   4.5]] [[ 0.35355339  0.63245553  0.35355339]]
[[ 4.5  3.   4.5]] [[ 0.35355339  0.4472136   0.35355339]]
-- average:
[[ 4.5  3.   4.5]] [[ 0.35355339  0.63245553  0.35355339]]
[[ 4.5  3.   4.5]] [[ 0.35355339  0.4472136   0.35355339]]
----------expected------------------------------
[[ 4.5  3.   4.5]] [[ 0.35355339  0.63245553  0.35355339]]
[[ 4.5  3.   4.5]] [[ 0.35355339  0.4472136   0.35355339]]
[[ 4.5  3.   4.5]] [[ 0.35355339  0.63245553  0.35355339]]
[[ 4.5  3.   4.5]] [[ 0.35355339  0.4472136   0.35355339]]
```
> ccdproc median combine

- AUTHORS.rst
- CHANGES.rst
- ccdproc/extern/bitfield.py
This PR enhances the treatment of very high bit flags in such a way that flags like `1<<63` (maximum supported by `uint64` type) now work and flags larger than maximum supported by `numpy.uint64` are ignored and again allow code to work without crashing. See #610 for more details.
>  Port enhancements to bitfield from stsci.tools

- docs/rtd-pip-requirements
I missed that in my earlier PR.
> Astropy > 2.0 for rtd pip-requirements

- .travis.yml
- appveyor.yml
Removes the following from CI:
- Python 2,7
- Astropy 1.x
And adds:
- NumPy 1.13 (which was untested since 1.14 has been released),
Given that Python 3.7 will be out soon we could also think about dropping Python 3.4.
Closes #511 and closes #613 and closes #615
> Remove astropy 1.0 and 1.3 and Python 2 from testing. Added test for Numpy 1.13

- CHANGES.rst
- ccdproc/_astropy_init.py
- ccdproc/core.py
- ccdproc/image_collection.py
- ccdproc/log_meta.py
- ccdproc/tests/test_ccdproc_logging.py
- ccdproc/tests/test_image_collection.py
- ccdproc/tests/test_keyword.py
After we dropped the tests for Python 2 this removes the most obvious compatibility places.
> Remove Python2 support by removing __future__ includes and six

- AUTHORS.rst
- CHANGES.rst
- ccdproc/image_collection.py
For bugfixes:
Astropy supports more formats of compressed images that are not included in the original version, commonly used by several observatories.
> Added compression formats supported by astropy

- .gitignore
No idea where the `.eggs` folder is coming from but it's probably not necessary to include it in the repo
> Ignore .vscode and .eggs folder in gitignore

- docs/license.rst
Fixed typo in license section of RTD.
Ignored all the questions placed on this area because I thought they didn't apply to this case.
> Fixed typo in license section

- ccdproc/combiner.py
This unifys the `scale` handling in the `*combine` methods by putting it in a separate method. It also simply returns the `data_arr` in case there is no scaling. This has a potentially huge advantage because in the common case that there is no scaling it doesn't do a copy. That copy could be several GB big (because it's a copy of the stacked ccds and the mask) so avoiding it when possible at least saves a bit of memory.
However I noticed that we don't use the scale for the uncertainty calculation, that probably warrants an own issue (or pull request). I tried to keep it to a simple refactor for this PR.
> Unify scale handling in the combine methods and avoid multiplying by 1 if none is given

- .travis.yml
- ccdproc/tests/pytest_fixtures.py
- ccdproc/tests/test_gain.py
This fixes #647 (some test failures against astropy dev and the 3.1 release candidate)
> Relax the array equality check in the gain tests

- .travis.yml
- appveyor.yml
- ccdproc/conftest.py
> Include Python 3.7 in test matrix

- docs/rtd-pip-requirements
This adds sphinx-astropy to the ReadTheDocs build requirements. If it fixes the builds, this closes #654 and closes #655
> Fix builds on RTD

- .travis.yml
- ah_bootstrap.py
This is an automated update of the astropy-helpers submodule to v3.2.1. This includes both the update of the astropy-helpers sub-module, and the ``ah_bootstrap.py`` file, if needed. 
Please note that since v3.2, ``sphinx-astropy`` needs to be explicitely listed as a dependency for building the documentation. 
A full list of changes can be found in the [changelog](https://github.com/astropy/astropy-helpers/blob/v3.2.1/CHANGES.rst). 
We also wanted to let you know that we have made new releases of the astropy package-template. You can find the latest [cookiecutter template here](https://github.com/astropy/package-template) or if you prefer you can find a [rendered version of the template here](https://github.com/astropy/package-template/tree/master). 
*This is intended to be helpful, but if …
> Update astropy-helpers to v3.2.1

- CHANGES.rst
- ccdproc/core.py
- ccdproc/tests/test_ccdproc.py
Fixes #674 by adding a check that the arrays have to be the same size.
> add error in subtract_dark for array differences

- docs/ccdproc/reduction_toolbox.rst
documentation update to include ccdmask in narrative docs.
closes #437
> add ccdmask to reduction toolbox documentation

- CHANGES.rst
- ccdproc/core.py
- ccdproc/tests/test_ccdproc.py
This adds a warning to `transform_images` that if a WCS is present, the transform is not applied to that WCS.
> added warning to transform_image that it does not apply to WCS

- CHANGES.rst
- ccdproc/core.py
- ccdproc/tests/test_ccdproc.py
Added an option to disregard negative values passed to ``create_deviation``and assume the error is represented by the read noise.  If not and there are negative values are in the array, a more informative warning is created.
Closes #573
> added better negative number handling to create_deviation

- CHANGES.rst
- ccdproc/image_collection.py
- ccdproc/tests/pytest_fixtures.py
- ccdproc/utils/sample_directory.py
- docs/image_management.rst
This fixes #699 by moving generation of a sample directory out of the tests and into utils.
> Move generation of test directory to utils

- README.rst
Fixes #708 
This updates the broken link mentioned in #708 and updates the links to use https instead of http.
> Update the links in README.rst

- .travis.yml
- ccdproc/conftest.py
- ccdproc/tests/test_ccdproc.py
- ccdproc/tests/test_wrapped_external_funcs.py
It seems like we shouldn't use `python:` but instead use the `PYTHON_VERSION` variable.
I also incremented the NumPy versions (no particular reason except that we were missing NumPy 1.15 and I think that would be more appropriate than NumPy 1.13).
Closes #706 
Ref: #707
> Fix CI problems

- AUTHORS.rst
- CHANGES.rst
- ccdproc/core.py
**My commit message used: [docs only], which I assume also behaves like [skip ci]**
For bugfixes:
Fixes #631 by clarifying the `sepmed` parameter is for performance only, and not part of the L.A. Cosmic algorithm natively. 
Also corrected typo of "lacosmic" to "L.A. Cosmic", per the original paper.
> update docs for lacosmic sepmed parameter [docs only]

- ccdproc/core.py
In astropy 4.1, these functions moved from the `nddata.utils` to the `nddata.blocks` module (https://github.com/astropy/astropy/pull/10214).  Importing from `nddata.utils` will still work, but will raise a deprecation warning.
> Update block_reduce and block_replicate imports

- AUTHORS.rst
- CHANGES.rst
- ccdproc/tests/test_bitfield.py
- ccdproc/tests/test_ccdmask.py
- ccdproc/tests/test_ccdproc.py
- ccdproc/tests/test_ccdproc_logging.py
- ccdproc/tests/test_combiner.py
- ccdproc/tests/test_cosmicray.py
- ccdproc/tests/test_gain.py
- ccdproc/tests/test_image_collection.py
- ccdproc/tests/test_keyword.py
- ccdproc/tests/test_memory_use.py
- ccdproc/tests/test_rebin.py
- ccdproc/tests/test_wrapped_external_funcs.py
This PR addresses issue [#735] by replacing relative imports in the test suite with absolute ones.
All tests passed with 46 warnings.
For bugfixes:
> Changed relative imports to absolute imports issue

- CHANGES.rst
- ccdproc/tests/test_image_collection.py
This commit addresses issue [#736], where `test_image_collection.py`
in the test suite generates a `test_table.txt` in the working directory
and does not clean up after itself. This is fixed now by using a
`NamedTemporaryFile` within a context manager, and deletes the file
once the test is completed.
For bugfixes:
> Using temporary files in tests

- .travis.yml
- AUTHORS.rst
- CHANGES.rst
- ccdproc/tests/run_with_file_number_limit.py
- setup.cfg
Fixes #730 by adding `memory_profiler` as a test requirement to `setup.cfg`. Also no longer ignores import errors in testing.
For bugfixes:
> Add memory_profiler as a test requirement [#730]

- docs/conf.py
This PR addresses #725 with a minor fix by providing the relevant `release` of ccdproc in the `html_title` which currently shows up as `vunknown` in the docs. This was done by importing `project` and accessing the `version` from it, which can also be seen done in other astropy affiliated packages like `photutils`, reference: [here](https://github.com/astropy/photutils/blob/master/docs/conf.py#L70-L76)
> Fix Read-the-docs ccdproc version

- AUTHORS.rst
- CHANGES.rst
- ccdproc/combiner.py
- ccdproc/tests/test_combiner.py
This PR  fixes #756 to be able to accept a `generator` instead of a `list` as argument to `Combine` and `combiner`.
1) The `generator` input has been converted into a list in the implementation since the idea of allowing a generator is mainly intended for user convenience.
2) The relevant `tests` and other corresponding necessary files have been modified.
3) The starting letter of all the comments in the changed files have been capitalized, wherever applicable, excluding when the comment starts with an identifier, following the PEP guidlines.
@mwcraig Could you please review the PR?
Thanks!!
<hr />
> Change `combine` and `Combiner` to accept a generator

- AUTHORS.rst
- CHANGES.rst
- ccdproc/image_collection.py
If the filtering criteria passed to ImageFileCollection.filter() would return
an empty collection, a crash occurs because the method instantiates a new
ImageFileCollection() with a list of filenames returned from .files_filtered().
When a new instance of ImageFileCollection() is called without a filenames
list, _get_files() -> _fits_files_in_directory() attempts to create a list
of all FITS files within the directory contained in self.location.  If this
new instance of ImageFileCollection() is called without setting location, then
self.location is set to "".  When _fits_files_in_directory() attempts to do a
directory listing via listdir(), an error is raised:
FileNotFoundError: [Errno 2] No such file or directory: ''
This commit adds a check for empty self.location before any attempted …
> Fix bug when ImageFileCollection.filter() would return an empty collection

- ccdproc.cfg
- ccdproc/__init__.py
- ccdproc/_astropy_init.py
- docs/default_config.rst
- docs/index.rst
This functionality will be deprecated in `astropy` in a future release. See astropy/astropy#11497 and https://groups.google.com/g/astropy-dev/c/KVzPgeihxO8
Bonus: Clean up test runner code.
> MNT: Do not write config on import

- .github/workflows/ci_tests.yml
- ccdproc/core.py
- ccdproc/extern/bitfield.py
- ccdproc/tests/test_combiner.py
- ccdproc/tests/test_cosmicray.py
- tox.ini
Turns out the `oldestdeps` tests were running with astropy `5` not the `4.0.6` requested. Also turns out that the combination of astroscrappy `1.0.8` and numpy `<1.20` is difficult so the `oldestdeps` test now uses numpy `1.20` which is not really the oldest supported one.
> Fix tox astropy dependency issue

- CHANGES.rst
- tox.ini
A warnign was happening during the documentation build because of   https://github.com/astropy/sphinx-automodapi/issues/141  (see [this failing run](https://github.com/astropy/ccdproc/runs/4757634889?check_suite_focus=true#step:7:79))
Once a release of `sphinx-automodapi` has been done the pin I added here for `sphinx-automodapi` version should be removed.
> Fix doc build warning

- ccdproc/conftest.py
- ccdproc/core.py
- ccdproc/tests/pytest_fixtures.py
- ccdproc/tests/run_for_memory_profile.py
- ccdproc/tests/test_bitfield.py
- ccdproc/tests/test_ccdproc.py
- ccdproc/tests/test_image_collection.py
- ccdproc/tests/test_rebin.py
For bugfixes:
This pull request is to remove soon to be deprecated code; also see astropy/astropy#12633 .
> MNT: Stop using deprecated astropy.tests stuff

- AUTHORS.rst
- CHANGES.rst
- ccdproc/core.py
This PR fixes issue #786.
In python 3.7 the ``version`` method from ``packaging`` must be imported directly.
For bugfixes:
> Bugfix to issue #786

- AUTHORS.rst
- CHANGES.rst
- ccdproc/combiner.py
- ccdproc/tests/test_combiner.py
- setup.cfg
This switches the sigma clipping to always use the astropy sigma clipping, and default to using strings for the statistics/functions to use by default as this provides the best performance. This requires bumping the minimum version of astropy to 4.3 which I hope should be ok now that LTS is now 5.x?
I haven't done extensive testing beyond the built-in test suite and my own use case, but for my case the sigma clipping became almost 3x faster.
Fixes https://github.com/astropy/ccdproc/issues/793
I also think https://github.com/astropy/ccdproc/issues/753 could be closed with this merged.
Perhaps https://github.com/astropy/ccdproc/issues/624 would also be resolved by this? (but make sure you change the functions for sigma clipping to be strings)
> Always use astropy's sigma clipping and default to string-based functions

- CHANGES.rst
- ccdproc/combiner.py
- ccdproc/tests/test_combiner.py
Add an optional keyword argument to ``ccdproc.combiner.combine()`` to allow for the overwrite of the optional ``output_file``.  The default value of ``overwrite_output = False`` is identical to current behavior, and the user would need to specify this keyword argument as ``True`` to allow overwriting.
modified:   ccdproc/combiner.py
For bugfixes:
> Allow overwrite of ``output_file`` in ``ccdproc.combiner.combine()``

- AUTHORS.rst
- setup.cfg
ccdproc requires astropy 5.0.1 which forces dropping python 3.7 compatibility
edit: fixes #798
> Increment minimum astropy version

- setup.cfg
- tox.ini
There were two problems here:
- No wheel for numpy 1.20 and python 3.8
- numpy must install before astroscrappy for the astroscrappy source build to succeed.
> Fix the tox test for oldest dependencies

- setup.cfg
This fixes #805 by ensuring that the version of pytest-remotedata that is used is 0.3.3, the first version which switched from distutils to packaging for version number handling.
> Update the mimnimum required version for pytest-astropy

- CHANGES.rst
- ccdproc/image_collection.py
- ccdproc/tests/test_image_collection.py
The ``files_filtered()`` method chokes on a ``'NoneType' object is not subscriptable`` error if the ImageFileCollection is already empty before being asked to filter further.
This commit adds a check for an empty IFC and simply passes an empty list for the set of files in the collection.
modified:   CHANGES.rst
modified:   ccdproc/image_collection.py
For bugfixes:
> Add check for empty IFC in filtering

- .github/workflows/ci_tests.yml
- ccdproc/tests/test_cosmicray.py
- ccdproc/tests/test_image_collection.py
- setup.cfg
This should resolve the current CI instability. ([example logs](https://github.com/astropy/ccdproc/actions/runs/8575940098/job/23505969612?pr=819))
For context, what I think is happening is that the `pytest.warns` context manager's behavior was changed in pytest 8.0. In older versions, all warnings *other* than the one we were checking for were silently swallowed, and now they're not. In this specific test, `astropy` would also emit some `AstropyUserWarning`(s), which we don't control but are pointing to the very same problem we're testing for, so we should just filter them explicitly.
> TST: fix compatibility with pytest 8

- .readthedocs.yml
- docs/rtd-pip-requirements
I noticed RTD builds were failing with
```
Error
Config validation error in build.os. Value os not found.
```
([example logs](https://readthedocs.org/projects/ccdproc/builds/23995793/))
I think it's just a matter of configuration format.
For context: https://test-githubblog.readthedocs.io/en/latest/migrate-configuration-v2/
> DOC: migrate ReadTheDocs configuration file to v2

- ccdproc/extern/bitfield.py
Fixes #818, but doesn't yet allow testing against numpy 2: astroscrappy needs a compatible release before that.
> Avoid using np.maximum_sctype (dropped in NumPy 2)

- .github/workflows/ci_tests.yml
- tox.ini
> TST: add CI coverage for Python 3.11 and 3.12

- ccdproc/image_collection.py
- ccdproc/tests/test_image_collection.py
While testing the package, I stumbled upon a `_ASTROPY_LT_1_3` constant so I pulled the thread.
> DEPR: deprecate 'clobber' alias for overwrite keyword argument

- ccdproc/tests/test_ccdproc.py
There are a couple other failing tests with numpy 2 but this one is self contained.
I'll open a different PR for the rest.
> BUG: fix compatibility with numpy 2.0.0 (copy semantics)

- ccdproc/tests/test_combine_open_files.py
These can be removed now that Python < 3.5 isn't supported anymore
> TST: cleanup unused pytest.skip decorators

- ccdproc/tests/test_combine_open_files.py
I scratched my head a couple minutes as I tried to understand why these tests were failing locally against numpy 2. Turns out, the error was trivial and had nothing to do with numpy:
```
ModuleNotFoundError: No module named 'psutil'
```
but it originally was not visible in pytest logs, so I propose to let stderr propagate naturally in this context to help future debugging.
> TST: avoid capturing stderr in tests using subprocesses

- docs/ccddata.rst
This is similar to https://github.com/astropy/astropy/pull/15065
Since there is no simple way to have these doctests pass with both versions of numpy, my understanding is that this should be merged after numpy 2.0.0 final comes out.
xref: https://numpy.org/devdocs/release/2.0.0-notes.html#representation-of-numpy-scalars-changed
> DOC: adapt a docstest for numpy 2 (representation of scalars changed)

- AUTHORS.rst
Following @mwcraig's request at https://github.com/astropy/ccdproc/pull/826#issuecomment-2049851206
> DOC: add myself (Clément M.T. Robert) to AUTHORS.md

- ccdproc/core.py
Somehow I missed these in #826
> DOC: adapt a docstest for numpy 2 (representation of scalars changed) (round 2)

- tox.ini
I noticed CI was broken since numpy 2.0 was released: [example logs](https://github.com/astropy/ccdproc/actions/runs/9542750335/job/26298102524)
This should address it.
> TST: pin numpy<2 for tests with old astroscrappy

- AUTHORS.rst
- CHANGES.rst
- ccdproc/core.py
> Fixes #796 - cosmicray_lacosmic data type return

- .github/workflows/ci_tests.yml
- pyproject.toml
- tox.ini
This drops testing on several no-longer-supported versions of numpy.
> Update test matrix for newer versions of numpy

- .github/dependabot.yml
- .github/workflows/ci_tests.yml
> Workflow maintainance

- CHANGES.rst
- ccdproc/core.py
- ccdproc/tests/test_ccdproc.py
> Remove plain numpy array as argument option

- CHANGES.rst
- ccdproc/core.py
- ccdproc/tests/test_ccdproc.py
> Remove unused private function

- .github/workflows/ci_tests.yml
- AUTHORS.rst
- ccdproc/tests/make_mef.py
- ccdproc/tests/pytest_fixtures.py
- ccdproc/tests/run_for_memory_profile.py
- ccdproc/tests/run_with_file_number_limit.py
- ccdproc/tests/test_bitfield.py
- ccdproc/tests/test_ccdproc.py
- ccdproc/tests/test_cosmicray.py
- ccdproc/tests/test_rebin.py
- ccdproc/tests/test_wrapped_external_funcs.py
- docs/ccddata.rst
- docs/getting_started.rst
- docs/image_combination.rst
- docs/reduction_toolbox.rst
> Update Numpy RNG calls.  Fixes #839

- ccdproc/tests/test_ccdproc.py
- ccdproc/tests/test_combiner.py
- ccdproc/tests/test_image_collection.py
- ccdproc/tests/test_rebin.py
- ccdproc/tests/test_wrapped_external_funcs.py
- ccdproc/utils/tests/test_slices.py
> Use more appropriate comparison for floating point tests
